apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: node-rolling
spec:
  version: "v1.0.0"
  platforms:
  - selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin, linux]}
    uri: https://github.com/yogeek/kubectl-node-rolling/releases/download/v1.0.0/v1.0.0.zip
    sha256: "add1a4e9ce70d820da29641db05abddd55cdfa84a0da3b36b99f1b1b66775b5d"
    files:
    - from: "*.sh"
      to:  "."
    bin: "node-rolling.sh"
  shortDescription: >-
    Shutdown cluster nodes sequentially & gracefully
  homepage: https://github.com/yogeek/kubectl-node-rolling
  caveats: |
    Execution of this plugin requires Kubernetes cluster-admin Rolebindings
    and the ability to schedule Privileged Pods.
  description: |
    This plugin performs a sequential, rolling shutdown of selected nodes by first
    draining each node, then running a Kubernetes Job to shutdown each node, and
    finally waiting for the node to be replaced by a new one 
    by an external component (like an AutoScaling Group). 
